[api]
url = "https://api-fxtest.oanda.com"
account_id = "111-222-33333333-444"
access_token = "token-test"

[db]
host = "localhost"
port = "5432"
user_name = "test"
password = "test"
db_name = "test_db"